### ISSUE TITLE
Add vinted.nl ?

### ISSUE THREAD

**Issue by Bug-Ninja** [tobiasfrck/favorites_filter_vinted#1]
thank you for writing this add-on! 

Wondering if it is possible to add vinted.nl to the domains? I'm asking, because I expected it to be working on my favourites page on vinted.nl. 

There are a lot more domains:
.at
.cz
.dk
.es
.fi
.fr
.gr
.hr
.ro
.sk
.se
and even more....

Wouldn't it be possible using "*://*.vinted.*/*" ? Or doesn't it work this way? (sorry, no experience with writing add-ons)

**Comment by tobiasfrck** [comment]
Hi, thanks for the feedback!
I will add support for the other domains.

I don't have much experience with programming add-ons myself, so I may be getting this wrong, but I don't think I can use a placeholder for TLDs.
I could ask permission for all sites, but that might make some users uncomfortable, which I can certainly understand and want to avoid.

**Comment by tobiasfrck** [comment]
Added supprt for 22 vinted domains in 64e1622. I uploaded an update to firefox addons and that is already approved.

**Comment by tobiasfrck** [comment]
Well, the addon "works" on vinted.nl but not really as the brand of an item is picked up as a size. This will need some more work I think.
